export const SELECT_PLATE = 'SELECT_PLATE'
export const ADD_PLATE = 'ADD_PLATE'
export const SHOW_SUMMARY = 'SHOW_SUMMARY'
export const DELETE_PLATE_FROM_ORDER = 'DELETE_PLATE_FROM_ORDER'
export const ORDER_DONE = 'ORDER_DONE'
export const RESET = 'RESET'
